name: Deploy static site to GitHub Pages

on:
  push:
    branches: [main]  # o "master" si tu rama principal se llama así

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create .nojekyll file
        run: touch docs/.nojekyll

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload static site
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2