name: Publicar gráfico en GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib kagglehub

      - name: Ejecutar script para generar gráfico
        run: |
          python plot.py

      - name: Mover gráfico a carpeta docs
        run: |
          mkdir -p docs
          cp grafica.png docs/

      - name: Subir carpeta docs a gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.1.3
        with:
          branch: gh-pages
          folder: docs
