name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs  # Apunta a tu carpeta `docs` donde están los archivos estáticos
          target_branch: gh-pages
          nojekyll: true  # Asegura que GitHub Pages no ejecute Jekyll